#line 2 "cml1_lexer.c"

#line 4 "cml1_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cml1_yy_create_buffer
#define yy_delete_buffer cml1_yy_delete_buffer
#define yy_flex_debug cml1_yy_flex_debug
#define yy_init_buffer cml1_yy_init_buffer
#define yy_flush_buffer cml1_yy_flush_buffer
#define yy_load_buffer_state cml1_yy_load_buffer_state
#define yy_switch_to_buffer cml1_yy_switch_to_buffer
#define yyin cml1_yyin
#define yyleng cml1_yyleng
#define yylex cml1_yylex
#define yylineno cml1_yylineno
#define yyout cml1_yyout
#define yyrestart cml1_yyrestart
#define yytext cml1_yytext
#define yywrap cml1_yywrap
#define yyalloc cml1_yyalloc
#define yyrealloc cml1_yyrealloc
#define yyfree cml1_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cml1_yyrestart(cml1_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t cml1_yyleng;

extern FILE *cml1_yyin, *cml1_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cml1_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cml1_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cml1_yyrestart()), so that the user can continue scanning by
	 * just pointing cml1_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cml1_yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t cml1_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cml1_yywrap()'s to do buffer switches
 * instead of setting up a fresh cml1_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cml1_yyrestart (FILE *input_file  );
void cml1_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cml1_yy_create_buffer (FILE *file,int size  );
void cml1_yy_delete_buffer (YY_BUFFER_STATE b  );
void cml1_yy_flush_buffer (YY_BUFFER_STATE b  );
void cml1_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cml1_yypop_buffer_state (void );

static void cml1_yyensure_buffer_stack (void );
static void cml1_yy_load_buffer_state (void );
static void cml1_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cml1_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cml1_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cml1_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cml1_yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *cml1_yyalloc (yy_size_t  );
void *cml1_yyrealloc (void *,yy_size_t  );
void cml1_yyfree (void *  );

#define yy_new_buffer cml1_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cml1_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cml1_yy_create_buffer(cml1_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cml1_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cml1_yy_create_buffer(cml1_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *cml1_yyin = (FILE *) 0, *cml1_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int cml1_yylineno;

int cml1_yylineno = 1;

extern char *cml1_yytext;
#define yytext_ptr cml1_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cml1_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cml1_yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[318] =
    {   0,
        0,    0,    0,    0,    0,    0,   68,   60,   61,   65,
       66,   28,   60,   59,   60,   60,   60,   57,   57,   66,
       27,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   46,   46,   60,   60,   60,   46,   52,   67,   67,
       55,   67,   60,   61,   64,   29,   60,    0,   56,   60,
       60,   60,   59,   59,   60,   60,    0,    1,   26,   57,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       63,    0,   60,   60,   60,   60,   60,   60,   18,   60,
       20,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       52,    0,   55,    0,   54,   56,    0,   60,   60,   53,

       47,   60,   58,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   62,   60,   60,   60,   60,
       60,   60,   60,   19,   21,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   42,   60,   60,   60,    2,   60,
       60,   60,   60,   16,   60,   60,   60,   25,   60,   60,
       32,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   34,   60,   60,   60,   60,   36,   60,   39,

       60,   60,   60,   60,   60,   60,   60,    3,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   30,
       31,   60,   51,   60,   60,   35,   37,   38,   60,   60,
       60,   60,   60,   60,    4,   60,   60,   11,   12,   60,
       60,   60,   17,   60,   60,   60,   60,   60,   40,   60,
       60,   60,   44,   48,   60,   60,   60,   60,   60,   10,
       60,   60,   60,   60,   60,   33,   60,   49,   60,   45,
       60,   60,   60,   60,   60,   60,   13,   60,   60,   60,
       60,   60,   41,   43,   60,    6,    7,   60,   60,   14,
       60,   60,   60,   60,   50,    5,   60,   60,   60,   60,

       60,   60,   60,   60,   15,   60,   60,   24,    8,   60,
       22,   60,   60,   60,    9,   23,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    1,    1,    9,    1,
        1,    1,    1,    1,   10,    1,    1,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,    1,
       14,    1,    1,   15,   16,   17,   18,   17,   17,   19,
       20,   21,   22,   23,   23,   23,   23,   24,   25,   23,
       23,   26,   23,   23,   23,   23,   23,   23,   23,   23,
       13,   27,   13,    1,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   23,   23,   38,   39,   40,
       41,   42,   23,   43,   44,   45,   46,   47,   23,   48,
       49,   50,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[51] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[332] =
    {   0,
        0,    0,   49,   52,   54,   58,  529,    0,  526,  530,
      524,  512,   84,   61,  507,   57,   38,   57,   60,  530,
        0,  105,  499,   72,  482,   37,  489,   42,  484,  487,
       43,  490,   54,   43,   53,  478,    0,    0,  530,   85,
      530,   92,    0,  515,  530,    0,  100,   87,    0,  102,
      119,  124,   97,    0,  491,  141,  506,    0,    0,  105,
      144,  470,   90,  470,  469,  470,  481,  111,  472,  484,
      530,  504,  465,  464,  465,  124,  459,  470,    0,  453,
        0,  455,  462,  450,  459,  450,  452,  461,  456,  447,
        0,  142,  530,  161,  530,  530,  162,  177,  180,  530,

        0,  466,    0,  442,  452,  441,  433,  442,  438,  427,
      419,  420,  433,  417,  441,  530,  417,  414,  411,  399,
      407,  401,  394,    0,    0,  392,  386,  392,  386,  391,
      387,  382,  389,  179,  185,  402,  381,  384,  370,  367,
      374,  363,  361,  371,    0,  372,  365,  379,    0,  369,
      366,  356,  178,    0,  362,  355,  359,    0,  355,  345,
        0,  337,  336,  214,  219,  358,  336,  335,  340,  333,
      325,  331,  340,  343,  335,  337,  340,  326,  315,  321,
      312,  319,  311,  320,  304,  305,  307,  313,  314,  309,
      306,  311,    0,  224,  227,  313,  287,    0,  286,    0,

      295,  286,  281,  295,  291,  285,  294,    0,  276,  292,
      278,  270,  270,  273,  270,  269,  259,  264,  259,    0,
        0,  254,    0,  237,  270,    0,    0,    0,  254,  263,
      257,  262,  260,  264,    0,  222,  254,    0,    0,  249,
      252,  244,    0,  240,  246,  251,  274,  302,    0,  239,
      249,  248,    0,  329,  236,  242,  228,  218,  219,    0,
      223,  220,  211,  227,  214,    0,  356,  383,  203,    0,
      215,  204,  196,  197,  193,  197,    0,  196,  199,  101,
      191,  410,    0,    0,  181,    0,    0,  181,  169,    0,
      166,  181,  160,  161,    0,    0,  160,  154,  163,  156,

      149,  139,  145,  143,    0,  138,  133,    0,    0,  114,
        0,  112,  102,   69,    0,    0,  530,  437,  442,  106,
      447,  452,  457,  462,  467,  472,  477,  482,  102,   93,
      487
    } ;

static yyconst flex_int16_t yy_def[332] =
    {   0,
      317,    1,  318,  318,  319,  319,  317,  320,  317,  317,
      317,  320,  321,  322,  320,  323,  320,  320,  320,  317,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  324,  317,  325,
      317,  325,  320,  317,  317,  320,  321,  326,  320,  321,
      321,  321,  322,  327,  320,  323,  328,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      317,  317,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      324,  325,  317,  325,  317,  317,  326,  321,  321,  317,

      320,  320,   61,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  317,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  321,  321,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  321,  321,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  321,  321,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  321,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  329,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  321,  330,  320,  320,
      320,  320,  320,  329,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  331,  330,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  331,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,    0,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317
    } ;

static yyconst flex_int16_t yy_nxt[581] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,    8,    8,   23,    8,    8,
        8,    8,    8,    8,    8,    8,   24,    8,    8,   25,
       26,   27,   28,   29,    8,   30,   31,    8,   32,   33,
        8,    8,    8,   34,   35,   36,    8,    8,   37,    8,
       39,   39,   39,   39,   39,   39,   39,   39,   57,   41,
       39,   39,   54,   41,   54,   49,   58,   60,   60,   57,
       60,   60,   74,   54,   71,   72,   81,   75,   59,   77,
       42,   78,   82,   86,   42,   48,   84,   87,   88,   49,
       93,   50,   96,  268,   95,   89,   48,   93,   54,   85,

       54,   48,  254,   48,   61,   49,   43,   49,  316,   54,
       51,   94,   48,   97,   48,   60,   60,   98,   94,   99,
       48,  100,   52,   52,   49,   48,   51,  105,   51,  101,
      106,   48,   52,   62,  315,   63,   48,   64,   65,  111,
      292,  293,   57,  112,   66,   51,   67,   93,   68,   49,
       51,   69,  314,   57,  103,  103,  113,  120,  313,  103,
      103,  103,  103,   95,  100,  121,   93,   96,   94,  312,
      311,  310,  103,  103,  103,  103,  103,  103,   48,  309,
       48,   48,   49,  308,   49,   49,   48,   94,   97,   48,
       49,   48,   48,  307,  306,  305,  164,   48,  304,  303,

      302,  301,  134,   51,  135,   51,   51,  181,  165,  300,
      299,   51,  298,  182,  183,   48,  184,  297,  296,   49,
       48,  185,  186,  294,   49,   48,   48,  291,   48,  223,
      290,   48,   49,  289,  194,  288,   48,  195,   48,   48,
       51,  287,   49,  286,  285,   51,  284,  283,  224,   48,
       51,  255,  281,   51,  280,  279,  247,  256,  257,  278,
      277,  276,  275,   51,   43,  258,  259,  274,   43,   43,
       43,   43,   43,   43,  273,   48,  272,   43,   43,   49,
      271,  270,  269,  266,  265,  264,   48,  263,  262,  261,
       43,  260,  253,  252,  251,  250,  249,  248,  246,  245,

       51,  267,   43,  244,  243,  242,   43,   43,   43,   43,
       43,   43,  241,  240,  239,   43,   43,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,   43,   43,
      227,  226,  225,   43,   43,   43,   43,   43,   43,  222,
      221,  220,   43,   43,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,   43,   47,   48,  208,  207,
       47,   49,   47,   47,   47,   47,  206,  205,   48,   47,
       47,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      193,  192,   51,   43,  191,  190,  189,   43,   43,   43,
       43,   43,   43,  188,  187,  180,   43,   43,  179,  178,

      177,  176,  175,  174,  173,  172,  171,  170,  169,   43,
       47,   48,  168,  167,   47,  295,   47,   47,   47,   47,
      166,  163,   48,   47,   47,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,   51,   38,   38,   38,
       38,   38,   40,   40,   40,   40,   40,   47,   47,  151,
      150,   47,   53,   53,  149,   53,   53,   56,   56,  148,
      147,   56,   91,  146,  145,  144,   91,   92,   92,  143,
      142,   92,   48,   48,  141,  140,   48,   54,   54,  139,
       54,   54,   57,   57,  138,  137,   57,  282,  282,  136,
      133,  282,  132,  131,  130,  129,  128,  127,  126,  125,

      124,  123,  122,  119,  118,  117,  116,  115,  114,  110,
      109,  108,  107,  104,   96,  102,   44,   90,   83,   80,
       79,   76,   73,   70,   55,   46,   45,   44,  317,    7,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317
    } ;

static yyconst flex_int16_t yy_chk[581] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    4,    4,    4,    5,    5,   16,    5,
        6,    6,   14,    6,   14,   16,   17,   18,   18,   16,
       19,   19,   26,   14,   24,   24,   31,   26,   17,   28,
        5,   28,   31,   34,    6,   13,   33,   34,   35,   13,
       40,   13,   48,  330,   42,   35,   13,   42,   53,   33,

       53,   47,  329,   50,   18,   47,  320,   50,  314,   53,
       13,   40,   47,   48,   50,   60,   60,   50,   42,   50,
       51,   51,   13,   13,   51,   52,   47,   63,   50,   52,
       63,   51,   13,   22,  313,   22,   52,   22,   22,   68,
      280,  280,   56,   68,   22,   51,   22,   92,   22,   56,
       52,   22,  312,   56,   61,   61,   68,   76,  310,   61,
       61,   61,   61,   94,   97,   76,   94,   97,   92,  307,
      306,  304,   61,   61,   61,   61,   61,   61,   98,  303,
      134,   99,   98,  302,  134,   99,  135,   94,   97,   98,
      135,  134,   99,  301,  300,  299,  134,  135,  298,  297,

      294,  293,   98,   98,   99,  134,   99,  153,  135,  292,
      291,  135,  289,  153,  153,  164,  153,  288,  285,  164,
      165,  153,  153,  281,  165,  194,  164,  279,  195,  194,
      278,  165,  195,  276,  164,  275,  194,  165,  224,  195,
      164,  274,  224,  273,  272,  165,  271,  269,  195,  224,
      194,  236,  265,  195,  264,  263,  224,  236,  236,  262,
      261,  259,  258,  224,  234,  236,  236,  257,  234,  234,
      234,  234,  234,  234,  256,  247,  255,  234,  234,  247,
      252,  251,  250,  246,  245,  244,  247,  242,  241,  240,
      234,  237,  233,  232,  231,  230,  229,  225,  222,  219,

      247,  247,  248,  218,  217,  216,  248,  248,  248,  248,
      248,  248,  215,  214,  213,  248,  248,  212,  211,  210,
      209,  207,  206,  205,  204,  203,  202,  201,  248,  254,
      199,  197,  196,  254,  254,  254,  254,  254,  254,  192,
      191,  190,  254,  254,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  254,  267,  267,  178,  177,
      267,  267,  267,  267,  267,  267,  176,  175,  267,  267,
      267,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      163,  162,  267,  268,  160,  159,  157,  268,  268,  268,
      268,  268,  268,  156,  155,  152,  268,  268,  151,  150,

      148,  147,  146,  144,  143,  142,  141,  140,  139,  268,
      282,  282,  138,  137,  282,  282,  282,  282,  282,  282,
      136,  133,  282,  282,  282,  132,  131,  130,  129,  128,
      127,  126,  123,  122,  121,  120,  282,  318,  318,  318,
      318,  318,  319,  319,  319,  319,  319,  321,  321,  119,
      118,  321,  322,  322,  117,  322,  322,  323,  323,  115,
      114,  323,  324,  113,  112,  111,  324,  325,  325,  110,
      109,  325,  326,  326,  108,  107,  326,  327,  327,  106,
      327,  327,  328,  328,  105,  104,  328,  331,  331,  102,
       90,  331,   89,   88,   87,   86,   85,   84,   83,   82,

       80,   78,   77,   75,   74,   73,   72,   70,   69,   67,
       66,   65,   64,   62,   57,   55,   44,   36,   32,   30,
       29,   27,   25,   23,   15,   12,   11,    9,    7,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cml1_yy_flex_debug;
int cml1_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cml1_yytext;
#line 1 "cml1_lexer.l"
#line 2 "cml1_lexer.l"

/*
 *  gcml2 -- an implementation of Eric Raymond's CML2 in C
 *  Copyright (C) 2000-2001 Greg Banks
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Library General Public
 *  License along with this library; if not, write to the Free
 *  Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
 

#include <ctype.h>
#include "debug.h"
#define YY_NO_UNPUT 1	/* prevent compiler warning from unused fn */

CVSID2("$Id: cml1_lexer.l,v 1.5 2002/09/01 08:15:11 gnb Exp $");

/*============================================================*/

#if DEBUG
#define lineno_debug() \
    if (debug & DEBUG_LINENO) \
    	fprintf(stderr, "#line %s %d\n", yylocation.filename, yylocation.lineno)
#else
#define lineno_debug()
#endif

/* for handling multi-line prompts -- e.g. "choice" statements */
static char *qstring;
static int qstring_len;
/*============================================================*/

typedef struct
{
    cml_location location;  /* filename, lineno */
    FILE *filep;
    YY_BUFFER_STATE buffer;
} source_stack_rec;
/* stack of source_stack_rec, top first */
static GList *source_stack = 0;

static gboolean
yylex_push_file(const char *relfilename)
{
    source_stack_rec *rec;
    char *filename;
    FILE *fp;

    DDPRINTF1(DEBUG_INCLUDE, "pushing file \"%s\"\n", relfilename);
    
    /* record line number of `source' in old file, if any */
    if (source_stack != 0)
    {
	rec = (source_stack_rec *)source_stack->data;
	rec->location.lineno = yylocation.lineno;
    }
    
    filename = g_strdup(relfilename);
    if ((fp = fopen(filename, "r")) == 0)
    {
    	yyerror("can't open sourced file `%s': %s",
	    filename,
	    strerror(errno));
	g_free(filename);
    	return FALSE;
    }
    
    /* create new record */
    rec = g_new(source_stack_rec, 1);
    rec->location.filename = filename;
    rec->location.lineno = 1;
    rec->filep = fp;
    rec->buffer = cml1_yy_create_buffer(rec->filep,YY_BUF_SIZE);

    /* push new record */    
    source_stack = g_list_prepend(source_stack, rec);
    yylocation = rec->location;
    rb->filenames = g_list_prepend(rb->filenames, filename);
    cml1_yy_switch_to_buffer(rec->buffer);
    lineno_debug();
    
    return TRUE;
}

static int
cml1_yywrap(void)
{
    source_stack_rec *rec;

    /* pop off old top of stack */    
    assert(source_stack != 0);
    rec = (source_stack_rec *)source_stack->data;
    source_stack = g_list_remove_link(source_stack, source_stack);

    DDPRINTF1(DEBUG_INCLUDE, "popping file \"%s\"\n", rec->location.filename);
    
    /* delete old record and all forms of buffering */
    cml1_yy_delete_buffer(rec->buffer);
    fclose(rec->filep);
    /* don't free rec->filename yet, it's saved for rule & node locations */
    g_free(rec);
    
    /* revert to previous top if it exists */
    if (source_stack != 0)
    {
	rec = (source_stack_rec *)source_stack->data;
	cml1_yy_switch_to_buffer(rec->buffer);
	yylocation = rec->location;
	lineno_debug();
    	return FALSE;	    /* outer file to continue reading */
    }
    return TRUE;
}

/*============================================================*/

/*
 * Start conditions
 */
/* used to handle `source' for lexical inclusion */

/* used to handle multi-line prompts */

#line 838 "cml1_lexer.c"

#define INITIAL 0
#define CON_SOURCE 1
#define CON_MLPROMPT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cml1_yylex_destroy (void );

int cml1_yyget_debug (void );

void cml1_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE cml1_yyget_extra (void );

void cml1_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *cml1_yyget_in (void );

void cml1_yyset_in  (FILE * in_str  );

FILE *cml1_yyget_out (void );

void cml1_yyset_out  (FILE * out_str  );

yy_size_t cml1_yyget_leng (void );

char *cml1_yyget_text (void );

int cml1_yyget_lineno (void );

void cml1_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cml1_yywrap (void );
#else
extern int cml1_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( cml1_yytext, cml1_yyleng, 1, cml1_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cml1_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cml1_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cml1_yyin))==0 && ferror(cml1_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cml1_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cml1_yylex (void);

#define YY_DECL int cml1_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cml1_yytext and cml1_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 138 "cml1_lexer.l"


#line 1025 "cml1_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cml1_yyin )
			cml1_yyin = stdin;

		if ( ! cml1_yyout )
			cml1_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cml1_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cml1_yy_create_buffer(cml1_yyin,YY_BUF_SIZE );
		}

		cml1_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cml1_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 318 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 530 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 140 "cml1_lexer.l"
return K_AND;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 141 "cml1_lexer.l"
statement_start(); return K_BOOL;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 142 "cml1_lexer.l"
statement_start(); return K_CHOICE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "cml1_lexer.l"
statement_start(); return K_COMMENT;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 144 "cml1_lexer.l"
statement_start(); return K_DEFINE_BOOL;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 145 "cml1_lexer.l"
statement_start(); return K_DEFINE_HEX;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 146 "cml1_lexer.l"
statement_start(); return K_DEFINE_INT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 147 "cml1_lexer.l"
statement_start(); return K_DEFINE_STRING;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 148 "cml1_lexer.l"
statement_start(); return K_DEFINE_TRISTATE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 149 "cml1_lexer.l"
statement_start(); return K_DEP_BOOL;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 150 "cml1_lexer.l"
statement_start(); return K_DEP_HEX;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 151 "cml1_lexer.l"
statement_start(); return K_DEP_INT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 152 "cml1_lexer.l"
statement_start(); return K_DEP_MBOOL;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 153 "cml1_lexer.l"
statement_start(); return K_DEP_STRING;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 154 "cml1_lexer.l"
statement_start(); return K_DEP_TRISTATE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 155 "cml1_lexer.l"
return K_ELSE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 156 "cml1_lexer.l"
return K_ENDMENU;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 157 "cml1_lexer.l"
return K_FI;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 158 "cml1_lexer.l"
statement_start(); return K_HEX;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 159 "cml1_lexer.l"
return K_IF;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 160 "cml1_lexer.l"
statement_start(); return K_INT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 161 "cml1_lexer.l"
statement_start(); return K_MAINMENU_NAME;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 162 "cml1_lexer.l"
statement_start(); return K_MAINMENU_OPTION;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 163 "cml1_lexer.l"
return K_NEXT_COMMENT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 164 "cml1_lexer.l"
return K_NULL;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 165 "cml1_lexer.l"
return K_OR;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 166 "cml1_lexer.l"
return K_EQUALS;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 167 "cml1_lexer.l"
return K_NOT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 168 "cml1_lexer.l"
return K_NOT_EQUALS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 169 "cml1_lexer.l"
BEGIN(CON_SOURCE);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 170 "cml1_lexer.l"
statement_start(); return K_STRING;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 171 "cml1_lexer.l"
return K_THEN;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 172 "cml1_lexer.l"
statement_start(); return K_TRISTATE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 173 "cml1_lexer.l"
statement_start(); return K_UNSET;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 175 "cml1_lexer.l"
statement_start(); return K_TEST_ASSERT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 176 "cml1_lexer.l"
statement_start(); return K_TEST_CLEAR;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 177 "cml1_lexer.l"
statement_start(); return K_TEST_COMMIT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 178 "cml1_lexer.l"
statement_start(); return K_TEST_FREEZE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 179 "cml1_lexer.l"
statement_start(); return K_TEST_ERROR;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 180 "cml1_lexer.l"
statement_start(); return K_TEST_NOERROR;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 181 "cml1_lexer.l"
return K_TEST_PARSETEST;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 182 "cml1_lexer.l"
statement_start(); return K_TEST_SET;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 183 "cml1_lexer.l"
statement_start(); return K_TEST_SUCCEEDED;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 184 "cml1_lexer.l"
statement_start(); return K_TEST_VISIBLE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 185 "cml1_lexer.l"
statement_start(); return K_TEST_SAVEABLE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 187 "cml1_lexer.l"
{
		    yylval.string = g_strdup(cml1_yytext);
		    return TRISTATE;
		}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 192 "cml1_lexer.l"
{
    	    	    cml1_yytext[2] = '\0';
		    yylval.string = g_strdup(cml1_yytext+1);
		    return TRISTATE;
		}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 198 "cml1_lexer.l"
{
		    yylval.string = g_strdup(cml1_yytext);
		    return SYMBOL;
    	    	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 203 "cml1_lexer.l"
{
		    yylval.string = g_strdup(cml1_yytext+1);
		    return SYMBOLREF;
    	    	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 208 "cml1_lexer.l"
{
    	    	    cml1_yytext[cml1_yyleng-1] = '\0'; /* lose trailing quote */
		    yylval.string = g_strdup(cml1_yytext+2);
		    return SYMBOLREF;
    	    	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 214 "cml1_lexer.l"
{
    	    	    /* The undocumented $ARCH symbol is used in some rules */
    	    	    cml1_yytext[cml1_yyleng-1] = '\0'; /* lose trailing quote */
		    yylval.string = g_strdup(cml1_yytext+2);
		    if (rb_warning_enabled(rb, CW_SYMBOL_ARCH))
			cml_warningl(&yylocation, "undocumented symbol $ARCH used");
		    return SYMBOLREF;
    	    	}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 223 "cml1_lexer.l"
{
    	    	    /*
		     * Unquoted string immediately after `source' is filename
		     * to be lexically included.
		     */
    	    	    yylex_push_file(cml1_yytext);
		    BEGIN(0);
    	    	}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 232 "cml1_lexer.l"
{
    	    	    /* start of a multi-line prompt */
		    /*
		     * TODO: figure out if we actually need the qstring
		     *       variable or whether we can rely on yylval
		     *       across lex rules which do not return.
		     */
		    cml1_yytext[cml1_yyleng-2] = '\0';	/* lose backslash & newline */
    	    	    qstring = g_strdup(cml1_yytext+1);
		    qstring_len = cml1_yyleng-3;
		    ++yylocation.lineno;
		    lineno_debug();
		    BEGIN(CON_MLPROMPT);
    	    	}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 247 "cml1_lexer.l"
{
    	    	    /* continuation of a multi-line prompt */
		    /* Note: for some reason the corpus as of 2.5.20 comprised
		     *       51 double-quoted multiline prompts and no single
		     *       quoted ones;  I have taken this as indicative
		     *       of a hidden language rule and only implemented
		     *       double-quoted multiline prompts.
		     */
		    cml1_yyleng -= 2;
		    cml1_yytext[cml1_yyleng] = '\0';	/* lose backslash & newline */
		    qstring = g_realloc(qstring, qstring_len+cml1_yyleng+1);
		    strcpy(qstring+qstring_len, cml1_yytext);
		    qstring_len += cml1_yyleng;
		    ++yylocation.lineno;
		    lineno_debug();
    	    	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 264 "cml1_lexer.l"
{
    	    	    /* end of a multi-line prompt */
		    cml1_yyleng--;
    	    	    cml1_yytext[cml1_yyleng] = '\0';	/* lose trailing quote */
		    qstring = g_realloc(qstring, qstring_len+cml1_yyleng+1);
		    strcpy(qstring+qstring_len, cml1_yytext);
		    yylval.string = qstring;
		    BEGIN(0);
		    return PROMPT;
    	    	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 275 "cml1_lexer.l"
{
    	    	    /* single-line prompt, double-quoted or single-quoted */
		    if (!strncmp(cml1_yytext, "\"CONFIG_", 8) &&
		    	rb_warning_enabled(rb, CW_SYMBOL_LIKE_LITERAL))
		    	cml_warningl(&yylocation,
			    	"suspiciously symbol-like string literal %s",
				cml1_yytext);
    	    	    cml1_yytext[cml1_yyleng-1] = '\0';	/* lose trailing quote */
    	    	    yylval.string = g_strdup(cml1_yytext+1);
		    return PROMPT;
    	    	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 287 "cml1_lexer.l"
{
    	    	    yylval.string = g_strdup(cml1_yytext);
		    return DECIMAL;
    	    	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 292 "cml1_lexer.l"
{
    	    	    yylval.string = g_strdup(cml1_yytext);
		    return HEXADECIMAL;
		}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 297 "cml1_lexer.l"
{
    	    	    /* eat comments (matches to end of line or file) */
    	    	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 301 "cml1_lexer.l"
{
    	    	    yylval.string = g_strdup(cml1_yytext);
		    return WORD;
    	    	}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 306 "cml1_lexer.l"
/* eat whitespace */
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 309 "cml1_lexer.l"
{
    	    	    /* escaped newline */
    	    	    ++yylocation.lineno;
		    lineno_debug();
    	    	}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 315 "cml1_lexer.l"
{
    	    	    /* escaped newline */
    	    	    ++yylocation.lineno;
		    lineno_debug();
    	    	}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 321 "cml1_lexer.l"
{
    	    	    ++yylocation.lineno;
		    lineno_debug();
		    return EOL;
    	    	}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 327 "cml1_lexer.l"
{
    	    	    ++yylocation.lineno;
		    lineno_debug();
		    return EOL;
		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 333 "cml1_lexer.l"
{
    	    	    return cml1_yytext[0];
		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 337 "cml1_lexer.l"
ECHO;
	YY_BREAK
#line 1556 "cml1_lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CON_SOURCE):
case YY_STATE_EOF(CON_MLPROMPT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cml1_yyin at a new source and called
			 * cml1_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cml1_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cml1_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cml1_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cml1_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cml1_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cml1_yyrestart(cml1_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cml1_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 318 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 318 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 317);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cml1_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cml1_yyrestart(cml1_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cml1_yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cml1_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cml1_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cml1_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cml1_yy_create_buffer(cml1_yyin,YY_BUF_SIZE );
	}

	cml1_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	cml1_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cml1_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cml1_yypop_buffer_state();
	 *		cml1_yypush_buffer_state(new_buffer);
     */
	cml1_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cml1_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cml1_yywrap()) processing, but the only time this flag
	 * is looked at is after cml1_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cml1_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cml1_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cml1_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cml1_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cml1_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cml1_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cml1_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cml1_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cml1_yy_create_buffer()
 * 
 */
    void cml1_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cml1_yyfree((void *) b->yy_ch_buf  );

	cml1_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cml1_yyrestart() or at EOF.
 */
    static void cml1_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cml1_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cml1_yy_init_buffer was _probably_
     * called from cml1_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cml1_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cml1_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cml1_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cml1_yyensure_buffer_stack();

	/* This block is copied from cml1_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cml1_yy_switch_to_buffer. */
	cml1_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cml1_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cml1_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cml1_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cml1_yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cml1_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cml1_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cml1_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cml1_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cml1_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cml1_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cml1_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cml1_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cml1_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cml1_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE cml1_yy_scan_string (yyconst char * yystr )
{
    
	return cml1_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cml1_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cml1_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cml1_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cml1_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cml1_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cml1_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cml1_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cml1_yytext[cml1_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = cml1_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cml1_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cml1_yyget_lineno  (void)
{
        
    return cml1_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *cml1_yyget_in  (void)
{
        return cml1_yyin;
}

/** Get the output stream.
 * 
 */
FILE *cml1_yyget_out  (void)
{
        return cml1_yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t cml1_yyget_leng  (void)
{
        return cml1_yyleng;
}

/** Get the current token.
 * 
 */

char *cml1_yyget_text  (void)
{
        return cml1_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cml1_yyset_lineno (int  line_number )
{
    
    cml1_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cml1_yy_switch_to_buffer
 */
void cml1_yyset_in (FILE *  in_str )
{
        cml1_yyin = in_str ;
}

void cml1_yyset_out (FILE *  out_str )
{
        cml1_yyout = out_str ;
}

int cml1_yyget_debug  (void)
{
        return cml1_yy_flex_debug;
}

void cml1_yyset_debug (int  bdebug )
{
        cml1_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cml1_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cml1_yyin = stdin;
    cml1_yyout = stdout;
#else
    cml1_yyin = (FILE *) 0;
    cml1_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cml1_yylex_init()
     */
    return 0;
}

/* cml1_yylex_destroy is for both reentrant and non-reentrant scanners. */
int cml1_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cml1_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cml1_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	cml1_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cml1_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cml1_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cml1_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cml1_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see cml1_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 337 "cml1_lexer.l"



